Repository GenomicDataInfrastructure/gdi-userportal-frontend, pull requests merged in 2024-07, with the labels that each got.

#268 feat: remove specific color names + default values for fonts and colors
  .env.local.example
  src/app/DatasetCounter.tsx
  src/app/Disclaimer.tsx
  src/app/Footer.tsx
  src/app/Notification.tsx
  src/app/applications/[id]/FileUploadFormField.tsx
  src/app/applications/[id]/FileUploaded.tsx
  src/app/applications/[id]/FormContainer.tsx
  src/app/applications/[id]/InputFormField.tsx
  src/app/applications/[id]/TextAreaFormField.tsx
  src/app/applications/[id]/page.tsx
  src/app/basket/page.tsx
  src/app/datasets/FilterList/index.tsx
  src/app/datasets/[id]/DistributionAccordion.tsx
  src/app/datasets/page.tsx
  src/app/error.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/requests/applications/ApplicationItem.tsx
  src/app/requests/applications/DatasetList.tsx
  src/app/requests/applications/index.tsx
  src/components/Chip.tsx
  src/components/DatasetCard.tsx
  src/components/Header/Avatar.tsx
  src/components/Header/RequestIcon.tsx
  src/components/Header/index.tsx
  src/components/LinkItem.tsx
  src/components/List/ListItem.tsx
  src/components/LoadingContainer.tsx
  src/components/PageHeading.tsx
  src/components/PageSubHeading.tsx
  src/components/Searchbar.tsx
  src/components/Sidebar.tsx
  src/components/Tab.tsx
  src/components/shadcn/multipleSelector.tsx
  src/config/theme.ts
Labels: user story

#284 264 gdi frontend design and develop entitlement card
  src/app/requests/entitlements/EntitlementCard.tsx
  src/app/requests/entitlements/EntitlementsList.tsx
  src/components/DatasetCard.tsx
  src/components/DatasetList.tsx
Labels: enhancement

#306 feat: footer content is configurable by env vars
  .env.local.example
  src/app/Footer.tsx
  src/public/footer-logo.png
  src/public/footer-logo.png.license
Labels: user story

#318 feat: #272 review homepage layout
  src/app/page.tsx
  src/components/Searchbar.tsx
Labels: user story

#341 feat: #273 display Recents Datasets on homepage
  src/app/Footer.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/RecentDatasets.tsx
Labels: user story

#347 LNDC design for themes
  src/app/Footer.tsx
  src/app/about/page.tsx
  src/app/page.tsx
  src/components/Header/index.tsx
  src/components/RecentDatasets.tsx
  src/components/ThemesSection.tsx
Labels: user story

#350 feat: Themes Page and filter
  src/app/themes/page.tsx
  src/components/Header/index.tsx
  src/components/ThemesSection.tsx
Labels: user story

#354 fix: border and colour highlight
  src/app/applications/[id]/DateField.tsx
  src/app/applications/[id]/FileUploadFormField.tsx
  src/app/applications/[id]/FileUploaded.tsx
  src/app/applications/[id]/GenericInputField.tsx
  src/app/applications/[id]/TextAreaFormField.tsx
  src/components/PhoneInput.tsx
  src/components/shadcn/command.tsx
Labels: user story

#356 fix: hover and colour consistency on application form fields
  src/app/applications/[id]/DateField.tsx
  src/app/applications/[id]/FileUploadFormField.tsx
  src/app/applications/[id]/GenericInputField.tsx
  src/app/applications/[id]/TextAreaFormField.tsx
  src/components/PhoneInput.tsx
  src/components/shadcn/button.tsx
  src/components/shadcn/input.tsx
Labels: bug
